/**
 * pokedex画面でのリスト
 */

// Pokemonタイプリスト
export const typeList = [
  { type_id: 12, name: "Bug", background: "#729f3f" },
  { type_id: 16, name: "Dark", background: "#707070" },
  {
    type_id: 15,
    name: "Dragon",
    background: "linear-gradient(180deg, #53a4cf 50%, #f16e57 50%)",
  },
  { type_id: 4, name: "Electric", background: "#eed535", color: "#212121" },
  { type_id: 18, name: "Fairy", background: "#fdb9e9", color: "#212121" },
  { type_id: 7, name: "Fighting", background: "#d56723" },
  { type_id: 2, name: "Fire", background: "#fd7d24", color: "#ffffff" },
  {
    type_id: 10,
    name: "Flying",
    background: "linear-gradient(180deg, #3dc7ef 50%, #bdb9b8 50%)",
    color: "#212121",
  },
  { type_id: 14, name: "Ghost", background: "#7b62a3" },
  { type_id: 5, name: "Grass", background: "#9bcc50", color: "#212121" },
  {
    type_id: 9,
    name: "Ground",
    background: "linear-gradient(180deg, #f7de3f 50%, #ab9842 50%)",
    color: "#212121",
  },
  { type_id: 6, name: "Ice", background: "#51c4e7", color: "#212121" },
  { type_id: 1, name: "Normal", background: "#a4acaf", color: "#212121" },
  { type_id: 8, name: "Poison", background: "#b97fc9", color: "#ffffff" },
  { type_id: 11, name: "Psychic", background: "#f366b9" },
  { type_id: 13, name: "Rock", background: "#a38c21" },
  { type_id: 17, name: "Steel", background: "#9eb7b8", color: "#" },
  { type_id: 3, name: "Water", background: "#4592c4" },
];

// Pokemonタイプリスト
export const abilityList = [
  { id: 0, name: "All" },
  { id: 1, name: "Adaptability" },
  { id: 2, name: "Aerilate" },
  { id: 3, name: "Aftermath" },
  { id: 4, name: "Air Lock" },
  { id: 5, name: "Analytic" },
  { id: 6, name: "Anger Point" },
  { id: 7, name: "Anger Shell" },
  { id: 8, name: "Anticipation" },
  { id: 9, name: "Arena Trap" },
  { id: 10, name: "Armor Tail" },
  { id: 11, name: "Aroma Veil" },
  { id: 12, name: "As One" },
  { id: 13, name: "Aura Break" },
  { id: 14, name: "Bad Dreams" },
  { id: 15, name: "Ball Fetch" },
  { id: 16, name: "Battery" },
  { id: 17, name: "Battle Armor" },
  { id: 18, name: "Battle Bond" },
  { id: 19, name: "Beads of Ruin" },
  { id: 20, name: "Beast Boost" },
  { id: 21, name: "Berserk" },
  { id: 22, name: "Big Pecks" },
  { id: 23, name: "Blaze" },
  { id: 24, name: "Bulletproof" },
  { id: 25, name: "Cheek Pouch" },
  { id: 26, name: "Chilling Neigh" },
  { id: 27, name: "Chlorophyll" },
  { id: 28, name: "Clear Body" },
  { id: 29, name: "Cloud Nine" },
  { id: 30, name: "Color Change" },
  { id: 31, name: "Comatose" },
  { id: 32, name: "Commander" },
  { id: 33, name: "Competitive" },
  { id: 34, name: "Compound Eyes" },
  { id: 35, name: "Contrary" },
  { id: 36, name: "Corrosion" },
  { id: 37, name: "Costar" },
  { id: 38, name: "Cotton Down" },
  { id: 39, name: "Cud Chew" },
  { id: 40, name: "Curious Medicine" },
  { id: 41, name: "Cursed Body" },
  { id: 42, name: "Cute Charm" },
  { id: 43, name: "Damp" },
  { id: 44, name: "Dancer" },
  { id: 45, name: "Dark Aura" },
  { id: 46, name: "Dauntless Shield" },
  { id: 47, name: "Dazzling" },
  { id: 48, name: "Defeatist" },
  { id: 49, name: "Defiant" },
  { id: 50, name: "Delta Stream" },
  { id: 51, name: "Desolate Land" },
  { id: 52, name: "Disguise" },
  { id: 53, name: "Download" },
  { id: 54, name: "Dragon's Maw" },
  { id: 55, name: "Drizzle" },
  { id: 56, name: "Drought" },
  { id: 57, name: "Dry Skin" },
  { id: 58, name: "Early Bird" },
  { id: 59, name: "Earth Eater" },
  { id: 60, name: "Effect Spore" },
  { id: 61, name: "Electric Surge" },
  { id: 62, name: "Electromorphosis" },
  { id: 63, name: "Embody Aspect" },
  { id: 64, name: "Emergency Exit" },
  { id: 65, name: "Fairy Aura" },
  { id: 66, name: "Filter" },
  { id: 67, name: "Flame Body" },
  { id: 68, name: "Flare Boost" },
  { id: 69, name: "Flash Fire" },
  { id: 70, name: "Flower Gift" },
  { id: 71, name: "Flower Veil" },
  { id: 72, name: "Fluffy" },
  { id: 73, name: "Forecast" },
  { id: 74, name: "Forewarn" },
  { id: 75, name: "Friend Guard" },
  { id: 76, name: "Frisk" },
  { id: 77, name: "Full Metal Body" },
  { id: 78, name: "Fur Coat" },
  { id: 79, name: "Gale Wings" },
  { id: 80, name: "Galvanize" },
  { id: 81, name: "Gluttony" },
  { id: 82, name: "Good as Gold" },
  { id: 83, name: "Gooey" },
  { id: 84, name: "Gorilla Tactics" },
  { id: 85, name: "Grass Pelt" },
  { id: 86, name: "Grassy Surge" },
  { id: 87, name: "Grim Neigh" },
  { id: 88, name: "Guard Dog" },
  { id: 89, name: "Gulp Missile" },
  { id: 90, name: "Guts" },
  { id: 91, name: "Hadron Engine" },
  { id: 92, name: "Harvest" },
  { id: 93, name: "Healer" },
  { id: 94, name: "Heatproof" },
  { id: 95, name: "Heavy Metal" },
  { id: 96, name: "Honey Gather" },
  { id: 97, name: "Hospitality" },
  { id: 98, name: "Huge Power" },
  { id: 99, name: "Hunger Switch" },
  { id: 100, name: "Hustle" },
  { id: 101, name: "Hydration" },
  { id: 102, name: "Hyper Cutter" },
  { id: 103, name: "Ice Body" },
  { id: 104, name: "Ice Face" },
  { id: 105, name: "Ice Scales" },
  { id: 106, name: "Illuminate" },
  { id: 107, name: "Illusion" },
  { id: 108, name: "Immunity" },
  { id: 109, name: "Imposter" },
  { id: 110, name: "Infiltrator" },
  { id: 111, name: "Innards Out" },
  { id: 112, name: "Inner Focus" },
  { id: 113, name: "Insomnia" },
  { id: 114, name: "Intimidate" },
  { id: 115, name: "Intrepid Sword" },
  { id: 116, name: "Iron Barbs" },
  { id: 117, name: "Iron Fist" },
  { id: 118, name: "Justified" },
  { id: 119, name: "Keen Eye" },
  { id: 120, name: "Klutz" },
  { id: 121, name: "Leaf Guard" },
  { id: 122, name: "Levitate" },
  { id: 123, name: "Libero" },
  { id: 124, name: "Light Metal" },
  { id: 125, name: "Lightning Rod" },
  { id: 126, name: "Limber" },
  { id: 127, name: "Lingering Aroma" },
  { id: 128, name: "Liquid Ooze" },
  { id: 129, name: "Liquid Voice" },
  { id: 130, name: "Long Reach" },
  { id: 131, name: "Magic Bounce" },
  { id: 132, name: "Magic Guard" },
  { id: 133, name: "Magician" },
  { id: 134, name: "Magma Armor" },
  { id: 135, name: "Magnet Pull" },
  { id: 136, name: "Marvel Scale" },
  { id: 137, name: "Mega Launcher" },
  { id: 138, name: "Merciless" },
  { id: 139, name: "Mimicry" },
  { id: 140, name: "Mind's Eye" },
  { id: 141, name: "Minus" },
  { id: 142, name: "Mirror Armor" },
  { id: 143, name: "Misty Surge" },
  { id: 144, name: "Mold Breaker" },
  { id: 145, name: "Moody" },
  { id: 146, name: "Motor Drive" },
  { id: 147, name: "Moxie" },
  { id: 148, name: "Multiscale" },
  { id: 149, name: "Multitype" },
  { id: 150, name: "Mummy" },
  { id: 151, name: "Mycelium Might" },
  { id: 152, name: "Natural Cure" },
  { id: 153, name: "Neuroforce" },
  { id: 154, name: "Neutralizing Gas" },
  { id: 155, name: "No Guard" },
  { id: 156, name: "Normalize" },
  { id: 157, name: "Oblivious" },
  { id: 158, name: "Opportunist" },
  { id: 159, name: "Orichalcum Pulse" },
  { id: 160, name: "Overcoat" },
  { id: 161, name: "Overgrow" },
  { id: 162, name: "Own Tempo" },
  { id: 163, name: "Parental Bond" },
  { id: 164, name: "Pastel Veil" },
  { id: 165, name: "Perish Body" },
  { id: 166, name: "Pickpocket" },
  { id: 167, name: "Pickup" },
  { id: 168, name: "Pixilate" },
  { id: 169, name: "Plus" },
  { id: 170, name: "Poison Heal" },
  { id: 171, name: "Poison Point" },
  { id: 172, name: "Poison Puppeteer" },
  { id: 173, name: "Poison Touch" },
  { id: 174, name: "Power Construct" },
  { id: 175, name: "Power of Alchemy" },
  { id: 176, name: "Power Spot" },
  { id: 177, name: "Prankster" },
  { id: 178, name: "Pressure" },
  { id: 179, name: "Primordial Sea" },
  { id: 180, name: "Prism Armor" },
  { id: 181, name: "Propeller Tail" },
  { id: 182, name: "Protean" },
  { id: 183, name: "Protosynthesis" },
  { id: 184, name: "Psychic Surge" },
  { id: 185, name: "Punk Rock" },
  { id: 186, name: "Pure Power" },
  { id: 187, name: "Purifying Salt" },
  { id: 188, name: "Quark Drive" },
  { id: 189, name: "Queenly Majesty" },
  { id: 190, name: "Quick Draw" },
  { id: 191, name: "Quick Feet" },
  { id: 192, name: "Rain Dish" },
  { id: 193, name: "Rattled" },
  { id: 194, name: "Receiver" },
  { id: 195, name: "Reckless" },
  { id: 196, name: "Refrigerate" },
  { id: 197, name: "Regenerator" },
  { id: 198, name: "Ripen" },
  { id: 199, name: "Rivalry" },
  { id: 200, name: "RKS System" },
  { id: 201, name: "Rock Head" },
  { id: 202, name: "Rocky Payload" },
  { id: 203, name: "Rough Skin" },
  { id: 204, name: "Run Away" },
  { id: 205, name: "Sand Force" },
  { id: 206, name: "Sand Rush" },
  { id: 207, name: "Sand Spit" },
  { id: 208, name: "Sand Stream" },
  { id: 209, name: "Sand Veil" },
  { id: 210, name: "Sap Sipper" },
  { id: 211, name: "Schooling" },
  { id: 212, name: "Scrappy" },
  { id: 213, name: "Screen Cleaner" },
  { id: 214, name: "Seed Sower" },
  { id: 215, name: "Serene Grace" },
  { id: 216, name: "Shadow Shield" },
  { id: 217, name: "Shadow Tag" },
  { id: 218, name: "Sharpness" },
  { id: 219, name: "Shed Skin" },
  { id: 220, name: "Sheer Force" },
  { id: 221, name: "Shell Armor" },
  { id: 222, name: "Shield Dust" },
  { id: 223, name: "Shields Down" },
  { id: 224, name: "Simple" },
  { id: 225, name: "Skill Link" },
  { id: 226, name: "Slow Start" },
  { id: 227, name: "Slush Rush" },
  { id: 228, name: "Sniper" },
  { id: 229, name: "Snow Cloak" },
  { id: 230, name: "Snow Warning" },
  { id: 231, name: "Solar Power" },
  { id: 232, name: "Solid Rock" },
  { id: 233, name: "Soul-Heart" },
  { id: 234, name: "Soundproof" },
  { id: 235, name: "Speed Boost" },
  { id: 236, name: "Stakeout" },
  { id: 237, name: "Stall" },
  { id: 238, name: "Stalwart" },
  { id: 239, name: "Stamina" },
  { id: 240, name: "Stance Change" },
  { id: 241, name: "Static" },
  { id: 242, name: "Steadfast" },
  { id: 243, name: "Steam Engine" },
  { id: 244, name: "Steelworker" },
  { id: 245, name: "Steely Spirit" },
  { id: 246, name: "Stench" },
  { id: 247, name: "Sticky Hold" },
  { id: 248, name: "Storm Drain" },
  { id: 249, name: "Strong Jaw" },
  { id: 250, name: "Sturdy" },
  { id: 251, name: "Suction Cups" },
  { id: 252, name: "Super Luck" },
  { id: 253, name: "Supersweet Syrup" },
  { id: 254, name: "Supreme Overlord" },
  { id: 255, name: "Surge Surfer" },
  { id: 256, name: "Swarm" },
  { id: 257, name: "Sweet Veil" },
  { id: 258, name: "Swift Swim" },
  { id: 259, name: "Sword of Ruin" },
  { id: 260, name: "Symbiosis" },
  { id: 261, name: "Synchronize" },
  { id: 262, name: "Tablets of Ruin" },
  { id: 263, name: "Tangled Feet" },
  { id: 264, name: "Tangling Hair" },
  { id: 265, name: "Technician" },
  { id: 266, name: "Telepathy" },
  { id: 267, name: "Tera Shell" },
  { id: 268, name: "Tera Shift" },
  { id: 269, name: "Teraform Zero" },
  { id: 270, name: "Teravolt" },
  { id: 271, name: "Thermal Exchange" },
  { id: 272, name: "Thick Fat" },
  { id: 273, name: "Tinted Lens" },
  { id: 274, name: "Torrent" },
  { id: 275, name: "Tough Claws" },
  { id: 276, name: "Toxic Boost" },
  { id: 277, name: "Toxic Chain" },
  { id: 278, name: "Toxic Debris" },
  { id: 279, name: "Trace" },
  { id: 280, name: "Transistor" },
  { id: 281, name: "Triage" },
  { id: 282, name: "Truant" },
  { id: 283, name: "Turboblaze" },
  { id: 284, name: "Unaware" },
  { id: 285, name: "Unburden" },
  { id: 286, name: "Unnerve" },
  { id: 287, name: "Unseen Fist" },
  { id: 288, name: "Vessel of Ruin" },
  { id: 289, name: "Victory Star" },
  { id: 290, name: "Vital Spirit" },
  { id: 291, name: "Volt Absorb" },
  { id: 292, name: "Wandering Spirit" },
  { id: 293, name: "Water Absorb" },
  { id: 294, name: "Water Bubble" },
  { id: 295, name: "Water Compaction" },
  { id: 296, name: "Water Veil" },
  { id: 297, name: "Weak Armor" },
  { id: 298, name: "Well-Baked Body" },
  { id: 299, name: "White Smoke" },
  { id: 300, name: "Wimp Out" },
  { id: 301, name: "Wind Power" },
  { id: 302, name: "Wind Rider" },
  { id: 303, name: "Wonder Guard" },
  { id: 304, name: "Wonder Skin" },
  { id: 305, name: "Zen Mode" },
  { id: 306, name: "Zero to Hero" },
];

export const sortList = [
  { id: 'asc', name: "Lowest Number (First)" },
  { id: 'desc', name: "Highest Number (First)" },
  { id: 'A-Z', name: "A-Z" },
  { id: 'Z-A', name: "Z-A" },
];