spring:
 datasource:
  url: jdbc:mysql://localhost:3306/pokedexdb?connectionTimeZone=SERVER
  username: develop
  password: develop
 jpa:
  hibernate:
    ddl-auto: update
 sql:
  init:
   mode: always
   encoding: UTF-8
 security:
  jwt:
   token:
    secret-key: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    expire-length: 604800000
      
# logging:
#  level:
#   root: info
#  file:
#   name: logs/app.log

